site_name: Paradocs

nav:
  - 'index.md'
  - 'policies.md'
  - 'schema.md'
  - 'struct.md'
  - 'form_objects_dsl.md'
  - 'subschema.md'
  - 'documentation_generation.md'
  - 'custom_configuration.md'
  - 'faq.md'

